Task/littera test turborepo
Littera-Education/littera-github-actions pull request #81
Opened 2024-04-15 18:56 UTC by jsmylnycky

Example job that deploys all apps that have changed once merged to main:
https://github.com/Littera-Education/littera-test-turborepo/actions/runs/8693804845

Example job deploying:
https://github.com/Littera-Education/littera-test-turborepo/actions/runs/8694455795

Example of PR validations:
https://github.com/Littera-Education/littera-test-turborepo/actions/runs/8694497896

2024-04-15 19:07 UTC, chrislittera requested changes

2024-04-15 19:07 UTC, chrislittera commented on .github/workflows/turbo-deploy.yml
> +          vercel-version: 33.7.0
vercel cli version should be a configurable option that defaults to `33.4.0` <- stays consistent with the default value of the other job calling it here: https://github.com/Littera-Education/littera-github-actions/blob/develop/.github/workflows/vercel-deploy.yml#L32

2024-04-16 13:48 UTC, chrislittera approved these changes

2024-04-16 14:07 UTC, saad-littera approved these changes

2024-04-16 14:09 UTC, merged